---
title: "test_runs"
author: "Gaojia Xu"
date: '2022-04-15'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(R.matlab)
```


```{r}
n_init <- 15
set.seed(123)
X_raw <- matrix(runif(n_init*6), ncol=6)
```

```{r}
convert_scale <- function(OldMax=1, OldMin=0, OldValue, NewMax, NewMin){
  OldRange = (OldMax - OldMin)  
  NewRange = (NewMax - NewMin)  
  NewValue = (((OldValue - OldMin) * NewRange) / OldRange) + NewMin
}

convert_vars <- function(oldmatrix){
  young <- mapply(convert_scale, OldValue = oldmatrix[,1], NewMax = 300e9, NewMin=200e9)
  poisson <- mapply(convert_scale, OldValue = oldmatrix[,2], NewMax = 0.1, NewMin=0.49)
  CTE <- mapply(convert_scale, OldValue = oldmatrix[,3], NewMax = 5e-6, NewMin=1.5e-5)
  thermal <- mapply(convert_scale, OldValue = oldmatrix[,4], NewMax = 5, NewMin=15)
  temp <- mapply(convert_scale, OldValue = oldmatrix[,5], NewMax = 50, NewMin=360)
  pressure <- mapply(convert_scale, OldValue = oldmatrix[,6], NewMax = 1e5, NewMin=4.8e5)
  newmatrix <- matrix(c(young, poisson, CTE, thermal, temp, pressure),
                      byrow=F, ncol=6)
return(newmatrix)
}
```

```{r}
X_init <- convert_vars(X_raw)
```


# open matlab connection

```{r}
Matlab$startServer()
matlab <- Matlab()
isOpen <- open(matlab)
if (!isOpen) throw("MATLAB server is not running: waited 30 seconds.")
```

```{r}
simulator <- function(input){
  ymod <- input[1]
  prat <- input[2]
  cte <- input[3]
  therm <- input[4]
  ctemp <- input[5]
  press <- input[6]
  # set a variable in R and send to MATLB
  setVariable(matlab,
              ymod = ymod,
              prat = prat,
              cte = cte,
              therm = therm,
              ctemp = ctemp,
              press = press)
  
  evaluate(matlab, "[stress,displ] = simulator(ymod,prat,cte,therm,ctemp,press)")
  
  return(c(getVariable(matlab, "stress")$stress,getVariable(matlab, "displ")$displ))
}
```

```{r}
count = 1
y = matrix(nrow  = n_init, ncol = 2)
```

##############
```{r}
y_curr = simulator(X_init[count,])
```

```{r}
y[count, ] = y_curr
```
```{r}
(count = count + 1)
```


```{r}
y
```
```{r}
write.csv(y,"x_init_unif.csv", row.names = FALSE)
```


















